server:
  port: 8083
  servlet:
    context-path: /loans
spring:
  application:
    name: loans
  datasource:
    url: jdbc:mysql://localhost:3306/db?allowPublicKeyRetrieval=true&useSSL=false
    username: user
    password: password
  jpa:
    show-sql: false
eureka:
  client:
    enabled: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/