server:
  port: 8080
eureka:
  client:
    enabled: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
spring.security:
  oauth2.resourceserver:
    jwt.jwk-set-uri : http://localhost:8180/realms/eazybankdev/protocol/openid-connect/certs
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      httpclient:
        connect-timeout: 1000
        response-timeout: 10s
